version: "3"
services:
  api:
    build: ./server
    ports:
      - "4000:4000"
    container_name: logika-api
    networks:
      - mongonet
  client:
    build: ./client
    ports:
      - "8080:8080"
    container_name: logika-client
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    container_name: logika-db
    networks:
      - mongonet
networks:
    mongonet:
        driver: bridge
